### ISSUE TITLE
Database

### ISSUE THREAD

**Issue by Mint-BKL** [Mint-BKL/YusakiBotV3#2]
Database's Properties
========
- File name: `grinder_list`
- File name: `schduled_jobs`
-------------
Stores user's data including..
-------------
- [x] User's ID (user_id)
- [x] User's Tier (user_tier)
- [x] Tasks
-------------
Usage
-------------
Stores when `grinder_add` `grinder_remove` `grinder_update` `schduled_jobs` is called

**Comment by RealYuri001** [comment]
Closing as this issue was solved.
